version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: viatab-postgres
    environment:
      POSTGRES_DB: viatab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./viatab-backend
    container_name: viatab-backend-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/viatab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build: ./viatab-frontend
    container_name: viatab-frontend-container
    ports:
      - "3000:80"

volumes:
  postgres-data:
